### ISSUE TITLE
Git submodule config does not work

### ISSUE THREAD

**Issue by leviadam** [tibetsprague/alchemy-client#2]
Following the intstrucations the submodule is not installed correctly.
I do see the reference in the `.gitmodules` file:
```
[submodule "lib/arc"]
	path = lib/arc
	url = https://github.com/daostack/daostack
```

But `git submodule init` or `update` do nothing.

**Comment by leviadam** [comment]
I think the answer might be [here](https://stackoverflow.com/a/9049703).

**Comment by tibetsprague** [comment]
Try now

**Comment by leviadam** [comment]
Working :)
